---
sidebar: sidebar 
permalink: download-gfc-resources.html 
keywords: global file cache, edge 
summary: Prima di iniziare a installare il software BlueXP edge caching Edge nelle sedi remote, è necessario conoscere molti requisiti. 
---
= Prima di iniziare a implementare le istanze di BlueXP edge caching Edge
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Prima di iniziare a installare il software BlueXP edge caching Edge nelle sedi remote, è necessario conoscere molti requisiti.



== Scaricare le risorse richieste

Scarica i modelli virtuali di caching edge BlueXP che intendi utilizzare nelle filiali, il pacchetto di installazione del software e la documentazione di riferimento aggiuntiva:

* Modello virtuale di Windows Server 2016:
+
https://repo.cloudsync.netapp.com/gfc/2k16-2_3_0-55.zip["Windows Server 2016 .OVA con NetApp GFC (VMware vSphere 6.5+)"^]
https://repo.cloudsync.netapp.com/gfc/2k16_GFC_2_3_0_55IMAGE.zip["Windows Server 2016 .VHDX con NetApp GFC (Microsoft Hyper-v)"^]

* Modello virtuale di Windows Server 2019:
+
https://repo.cloudsync.netapp.com/gfc/2k19-2_3_0-55.zip["Windows Server 2019 .OVA con NetApp GFC (VMware vSphere 6.5+)"^]
https://repo.cloudsync.netapp.com/gfc/2k19_GFC_2_3_0_55IMAGE.zip["Windows Server 2019 .VHDX con NetApp GFC (Microsoft Hyper-v)"^]

* Software BlueXP Edge Caching Edge:
+
https://repo.cloudsync.netapp.com/gfc/GFC-2-3-0-55-Release.exe["Pacchetto di installazione del software NetApp GFC (.EXE)"^]

* Dashboard Global file cache per Cloud Insights:
+
https://repo.cloudsync.netapp.com/gfc/ci-gfc-dashboards.zip["Dashboard NetApp GFC Cloud Insights (.ZIP)"]

* Documentazione Global file cache:
+
https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["Guida utente di NetApp Global file cache (.PDF)"^]



link:task-deploy-gfc-edge-instances.html#update-bluexp-edge-caching-edge-software["Attenersi alla procedura riportata di seguito"] Per aggiornare il software Edge di caching edge di BlueXP.


NOTE: Quando si implementa il caching edge BlueXP su Windows Server 2016, è necessario utilizzare .NET Framework 4.8 e Windows WebView2 Framework.



== Progettazione e implementazione di BlueXP edge caching Edge

A seconda dei requisiti, potrebbe essere necessario implementare una o più istanze Edge in base alle sessioni utente simultanee in una filiale. L'istanza Edge presenta la condivisione di file virtuale agli utenti finali all'interno della filiale, che è stata estesa in modo trasparente dall'istanza BlueXP edge caching Core associata. BlueXP edge caching Edge deve contenere un `D:\` Volume NTFS, che contiene i file memorizzati nella cache all'interno della filiale.


NOTE: Per BlueXP edge caching Edge, è importante comprendere link:concept-before-you-begin-to-deploy-gfc.html#sizing-guidelines["linee guida per il dimensionamento"]. In questo modo sarà possibile creare la progettazione corretta per l'implementazione del caching edge BlueXP. Inoltre, è necessario determinare la soluzione più adatta al proprio ambiente in termini di scalabilità, disponibilità delle risorse e ridondanza.



=== Istanza di BlueXP edge caching Edge

Quando si implementa un'istanza di Edge caching BlueXP, è necessario eseguire il provisioning di una singola macchina virtuale, implementando Windows Server 2016 Standard o Datacenter Edition, Windows Server 2019 Standard o Datacenter Edition, oppure utilizzando il caching edge `.OVA` oppure `.VHD` Modello, che include il sistema operativo Windows Server scelto e il software di caching edge BlueXP.



==== Passaggi rapidi

. Implementare il modello virtuale di caching edge BlueXP, Windows Server 2016 VM o Windows Server 2019 Standard o Datacenter Edition.
. Assicurarsi che la macchina virtuale sia connessa alla rete, collegata al dominio e accessibile tramite RDP.
. Installare il software BlueXP edge caching Edge più recente.
. Identificare il server di gestione del caching edge BlueXP e l'istanza Core.
. Configurare l'istanza di BlueXP edge caching Edge.




== Requisiti di BlueXP edge caching Edge

BlueXP edge caching Edge è progettato per funzionare su tutte le piattaforme che supportano Windows Server 2016 e 2019, offrendo UN IT semplificato alle sedi remote aziendali e oltre. In modo critico, il caching edge BlueXP può essere implementato nell'infrastruttura hardware esistente, nella virtualizzazione o negli ambienti di cloud ibrido/pubblico in quasi tutti i casi, se soddisfano alcuni requisiti di livello base.

Edge richiede le seguenti risorse hardware e software per funzionare in modo ottimale. Per ulteriori informazioni sulle linee guida generali sul dimensionamento, vedere link:concept-before-you-begin-to-deploy-gfc.html#sizing-guidelines["linee guida per il dimensionamento"].



=== Appliance server rinforzata

Il pacchetto di installazione di BlueXP edge caching crea un'appliance software avanzata su qualsiasi istanza di Microsoft Windows Server. _Non disinstallare_ il pacchetto BlueXP edge caching. La disinstallazione di BlueXP edge caching influisce sulla funzionalità dell'istanza del server e potrebbe richiedere una ricostruzione completa dell'istanza del server.



=== Requisiti hardware fisici

* Minimo 4 core CPU
* Minimo 16 GB di RAM
* NIC dedicata singola o ridondante a 1 Gbps
* Disco rigido SAS o SSD da 10.000 rpm (preferibile)
* Controller RAID con funzionalità di caching write-back attivata




=== Requisiti di implementazione virtuale

È noto che le piattaforme hypervisor sono soggette a peggioramento delle performance dal punto di vista di un sottosistema di storage (ad esempio, latenza). Per ottenere performance ottimali utilizzando il caching edge BlueXP, si consiglia di utilizzare un'istanza di server fisico con SSD.

Per ottenere le migliori performance negli ambienti virtuali, oltre ai requisiti degli host fisici, è necessario soddisfare i seguenti requisiti e riserve di risorse:

Microsoft Hyper-V 2012 R2 e versioni successive:

* Processore (CPU): Le CPU devono essere impostate su *statico*: Minimo: 4 core vCPU.
* Memoria (RAM): Minimo: 16 GB impostato come *statico*.
* Provisioning del disco rigido: I dischi rigidi devono essere configurati come *disco fisso*.


VMware vSphere 6.x e versioni successive:

* Processor (CPU): È necessario impostare la riserva dei cicli CPU. Minimo: 4 core vCPU @ 10000 MHz.
* Memoria (RAM): Minimo: 16 GB di spazio disponibile.
* Provisioning del disco rigido:
+
** Il provisioning dei dischi deve essere impostato su *thick provisioning ansioso azzerato*.
** Le condivisioni hard disk devono essere impostate su *High*.
** Devices.hotplug deve essere impostato su *False* utilizzando il client vSphere per impedire a Microsoft Windows di presentare dischi di caching edge BlueXP come rimovibili.


* Rete: L'interfaccia di rete deve essere impostata su *VMXNET3* (potrebbe essere necessario utilizzare VM Tools).


Edge funziona su Windows Server 2016 e 2019, quindi la piattaforma di virtualizzazione deve supportare il sistema operativo, oltre all'integrazione con utility che migliorano le performance del sistema operativo guest della macchina virtuale e la gestione della macchina virtuale, come VM Tools.



=== Requisiti di dimensionamento delle partizioni

* C: - Minimo 250 GB (volume di sistema/boot)
* D: Minimo 1 TB (volume di dati separato per Global file cache Intelligent file cache*)


*La dimensione minima è il doppio del set di dati attivo. Il volume cache (D:) può essere esteso ed è limitato solo dalle limitazioni del file system NTFS di Microsoft Windows.



=== Requisiti del disco Global file cache Intelligent file cache

La latenza del disco sul disco Global file cache Intelligent file cache (D:) deve garantire una latenza media dei dischi i/o inferiore a 0,5 ms e un throughput di 1 MiBps per utente simultaneo.

Per ulteriori informazioni, consultare https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["Guida utente di NetApp Global file cache"^].



=== Networking

* Firewall: Le porte TCP devono essere consentite tra le istanze di BlueXP edge caching Edge e Management Server e Core.
+
Porte TCP per caching edge BlueXP: 443 (HTTPS - LMS), 6618 - 6630.

* I dispositivi di ottimizzazione di rete (come Riverbed Steelhead) devono essere configurati per il pass-thru delle porte specifiche di caching edge BlueXP (TCP 6618-6630).




=== Best practice per workstation client e applicazioni

Il caching edge BlueXP si integra in modo trasparente negli ambienti dei clienti, consentendo agli utenti di accedere ai dati centralizzati utilizzando le workstation client, eseguendo applicazioni aziendali. Utilizzando il caching edge BlueXP, l'accesso ai dati avviene attraverso una mappatura diretta del disco o uno spazio dei nomi DFS. Per ulteriori informazioni su BlueXP edge caching fabric, Intelligent file Caching e sugli aspetti chiave del software, consultare link:concept-before-you-begin-to-deploy-gfc.html["Prima di iniziare a implementare il caching edge BlueXP"^] sezione.

Per garantire un'esperienza e performance ottimali, è importante rispettare i requisiti e le Best practice del client Microsoft Windows, come descritto nella Global file cache User Guide. Questo vale per tutte le versioni di Microsoft Windows.

Per ulteriori informazioni, consultare https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["Guida utente di NetApp Global file cache"^].



=== Best practice per firewall e antivirus

Sebbene il caching edge BlueXP faccia un ragionevole sforzo per verificare che le suite di applicazioni antivirus più comuni siano compatibili con Global file cache, NetApp non può garantire e non è responsabile di eventuali incompatibilità o problemi di performance causati da questi programmi o dai relativi aggiornamenti, service pack o modifiche.

NetApp sconsiglia l'installazione o l'applicazione di soluzioni antivirus o di monitoraggio su qualsiasi istanza abilitata per il caching edge BlueXP (Core o Edge). Nel caso in cui una soluzione venga installata, a scelta o in base a policy, è necessario applicare le seguenti Best practice e raccomandazioni. Per le suite antivirus più comuni, consultare l'Appendice A nella https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["Guida utente di NetApp Global file cache"^].



=== Impostazioni del firewall

* Firewall Microsoft:
+
** Mantenere le impostazioni predefinite del firewall.
** Consiglio: Lasciare le impostazioni e i servizi firewall Microsoft all'impostazione predefinita OFF e non avviarlo per le istanze standard di BlueXP edge caching Edge.
** Consiglio: Lasciare I servizi e le impostazioni firewall Microsoft impostate su ON e avviarle per le istanze di Edge che eseguono anche il ruolo di controller di dominio.


* Firewall aziendale:
+
** L'istanza di BlueXP edge caching Core è in attesa sulle porte TCP 6618-6630, assicurarsi che le istanze di BlueXP edge caching Edge possano connettersi a queste porte TCP.
** Le istanze di caching edge BlueXP richiedono comunicazioni con il server di gestione del caching edge BlueXP sulla porta TCP 443 (HTTPS).


* Le soluzioni/i dispositivi di ottimizzazione di rete devono essere configurati per passare attraverso le porte specifiche del caching edge BlueXP.




=== Best practice antivirus

NetApp ha testato i prodotti antivirus più comunemente utilizzati, tra cui Cylance, McAfee, Symantec, Sophos, Trend Micro, Kaspersky, Crowd Strike, Cisco AMP, Tannium e Windows Defender da utilizzare insieme al caching edge BlueXP. Il software antivirus deve essere certificato da NetApp ed è supportato solo se configurato con l'elenco di esclusione appropriato. Vedere l'Appendice A nella https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["Guida utente di NetApp Global file cache"^]


NOTE: L'aggiunta di un antivirus a un'appliance Edge può introdurre un impatto del 10-20% sulle performance degli utenti.

Per ulteriori informazioni, consultare https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["Guida utente di NetApp Global file cache"^].



==== Configurare le esclusioni

Il software antivirus o altre utilità di indicizzazione o scansione di terze parti non devono mai eseguire la scansione del disco D: Sull'istanza di Edge. Queste scansioni dell'unità edge server D: Comportano numerose richieste di apertura dei file per l'intero namespace della cache. In questo modo, i file fetch sulla WAN su tutti i file server vengono ottimizzati nel data center. Si verificherà un flooding della connessione WAN e un carico non necessario sull'istanza di Edge, con conseguente peggioramento delle performance.

Oltre al disco D:, la seguente directory e i seguenti processi di caching edge BlueXP dovrebbero essere generalmente esclusi da tutte le applicazioni antivirus:

* `C:\Program Files\TalonFAST\`
* `C:\Program Files\TalonFAST\Bin\LMClientService.exe`
* `C:\Program Files\TalonFAST\Bin\LMServerService.exe`
* `C:\Program Files\TalonFAST\Bin\Optimus.exe`
* `C:\Program Files\TalonFAST\Bin\tafsexport.exe`
* `C:\Program Files\TalonFAST\Bin\tafsutils.exe`
* `C:\Program Files\TalonFAST\Bin\tapp.exe`
* `C:\Program Files\TalonFAST\Bin\TappN.exe`
* `C:\Program Files\TalonFAST\Bin\FTLSummaryGenerator.exe`
* "C: File di programma TalonFAST Bin GfcCIAgentService.exe"
* `C:\Program Files\TalonFAST\Bin\RFASTSetupWizard.exe`
* `C:\Program Files\TalonFAST\Bin\TService.exe`
* `C:\Program Files\TalonFAST\Bin\tum.exe`
* `C:\Program Files\TalonFAST\FastDebugLogs\`
* `C:\Windows\System32\drivers\tfast.sys`
* `\\?\TafsMtPt:\` oppure `\\?\TafsMtPt*`
* `\Device\TalonCacheFS\`
* `\\?\GLOBALROOT\Device\TalonCacheFS\`
* `\\?\GLOBALROOT\Device\TalonCacheFS\*`




== Policy di supporto NetApp

Le istanze di edge caching BlueXP sono progettate specificamente come applicazione primaria in esecuzione su una piattaforma Windows Server 2016 e 2019. Il caching edge BlueXP richiede l'accesso prioritario alle risorse della piattaforma, ad esempio disco, memoria, interfacce di rete, e può porre richieste elevate su queste risorse. Le implementazioni virtuali richiedono riserve di memoria/CPU e dischi dalle performance elevate.

* Per le implementazioni delle filiali, i servizi e le applicazioni supportati sul server che esegue il caching edge BlueXP sono limitati a:
+
** DNS/DHCP
** Controller di dominio Active Directory (il caching edge BlueXP deve trovarsi su un volume separato)
** Servizi di stampa
** Microsoft System Center Configuration Manager (SCCM)
** BlueXP edge caching ha approvato agenti di sistema lato client e applicazioni antivirus


* Il supporto e la manutenzione NetApp si applicano solo al caching edge BlueXP.
* Software per la produttività delle linee di business, che in genere richiedono un uso intensivo delle risorse, ad esempio server di database, server di posta e così via, non sono supportati.
* Il cliente è responsabile di qualsiasi software di caching edge non BlueXP che potrebbe essere installato sul server che esegue il caching edge BlueXP:
+
** Se un pacchetto software di terze parti causa conflitti di software o risorse con il caching edge BlueXP o le prestazioni vengono compromesse, l'organizzazione di supporto NetApp potrebbe richiedere al cliente di disattivare o rimuovere il software dal server che esegue il caching edge BlueXP.
** È responsabilità del cliente per l'installazione, l'integrazione, il supporto e l'aggiornamento di qualsiasi software aggiunto al server che esegue l'applicazione di caching edge BlueXP.


* Le utility e gli agenti di gestione dei sistemi, come gli strumenti antivirus e gli agenti di licenza, potrebbero coesistere. Tuttavia, ad eccezione dei servizi e delle applicazioni supportati elencati in precedenza, queste applicazioni non sono supportate dal caching edge BlueXP e devono essere seguite le stesse linee guida di cui sopra:
+
** È responsabilità del cliente per l'installazione, l'integrazione, il supporto e l'aggiornamento di qualsiasi software aggiunto.
** Se un cliente installa un pacchetto software di terze parti che causa o si sospetta causi conflitti di software o risorse con il caching edge BlueXP o se le prestazioni sono compromesse, l'organizzazione di supporto di BlueXP edge caching potrebbe richiedere di disattivare/rimuovere il software.



