---
settings:
  name: BlueXP edge caching
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documenti per il caching edge BlueXP
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Novità
      url: "/whats-new.html"
    - title: Problemi risolti
      url: "/fixed-issues.html"
  - title: Inizia subito
    entries:
    - title: Scopri di più sul caching edge BlueXP
      url: "/concept-gfc.html"
    - title: Prerequisiti per il caching edge BlueXP
      url: "/concept-before-you-begin-to-deploy-gfc.html"
    - title: Implementare e concedere in licenza il caching edge BlueXP
      url: "/task-gfc-getting-started.html"
    - title: Prerequisiti di BlueXP edge caching Edge
      url: "/download-gfc-resources.html"
    - title: Implementare BlueXP edge caching Edge
      url: "/task-deploy-gfc-edge-instances.html"
  - title: Utilizzare il caching edge BlueXP
    entries:
    - title: Formazione per l'utente finale
      url: "/concept-gfc-enduser-training.html"
    - title: Ulteriori informazioni
      url: "/reference-gfc-additional-information.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere assistenza
      url: "/task-support-registration.html"
    - title: Richiedi assistenza
      url: "/task-get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
