---
settings:
  name: BlueXP edge caching
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documenti per il caching edge BlueXP
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Novità
      url: "/whats-new.html"
    - title: Problemi risolti
      url: "/fixed-issues.html"
  - title: Inizia subito
    entries:
    - title: Scopri di più sul caching edge BlueXP
      url: "/concept-gfc.html"
    - title: Prerequisiti per il caching edge BlueXP
      url: "/concept-before-you-begin-to-deploy-gfc.html"
    - title: Implementare e concedere in licenza il caching edge BlueXP
      url: "/task-gfc-getting-started.html"
    - title: Prerequisiti di BlueXP edge caching Edge
      url: "/download-gfc-resources.html"
    - title: Implementare BlueXP edge caching Edge
      url: "/task-deploy-gfc-edge-instances.html"
  - title: Utilizzare il caching edge BlueXP
    entries:
    - title: Formazione per l'utente finale
      url: "/concept-gfc-enduser-training.html"
    - title: Ulteriori informazioni
      url: "/reference-gfc-additional-information.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere assistenza
      url: "/task-support-registration.html"
    - title: Richiedi assistenza
      url: "/task-get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Inizia subito
    links:
    - title: Scopri di più sul caching edge BlueXP
      url: concept-gfc.html
    - title: Novità
      url: whats-new.html
    - title: Limitazioni
      url: concept-gfc.html#limitations
  - title: Implementare i componenti
    links:
    - title: Implementare Cloud Volumes ONTAP come piattaforma di storage
      url: task-gfc-getting-started.html#deploy-cloud-volumes-ontap-as-your-storage-platform
    - title: Implementare BlueXP edge caching Management Server e Core
      url: task-gfc-getting-started.html#enable-bluexp-edge caching-in-your-working-environment
    - title: Implementare istanze di BlueXP edge caching Edge
      url: task-deploy-gfc-edge-instances.html
  - title: Formare gli utenti
    links:
    - title: Formazione per l'utente finale
      url: concept-gfc-enduser-training.html
  - title: Blog e community
    links:
    - title: Community NetApp
      url: https://community.netapp.com/t5/BlueXP-and-Services/ct-p/CDS
    - title: Blog BlueXP
      url: https://bluexp.netapp.com/blog
    - title: Webinar sul cloud
      url: https://bluexp.netapp.com/events
  - title: Altre risorse
    links:
    - title: Casi di utilizzo di BlueXP Edge Caching
      url: https://bluexp.netapp.com/global-file-cache
product-family:
  name: BlueXP
  repo: bluexp-family
  sidebar_label: Tutta la documentazione BlueXP
