---
sidebar: sidebar 
permalink: reference-gfc-additional-information.html 
keywords: global file cache 
summary: Utilizza i seguenti link per saperne di più sul caching edge BlueXP e su altri prodotti NetApp. 
---
= Ulteriori informazioni
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilizza i seguenti link per saperne di più sul caching edge BlueXP e su altri prodotti NetApp:

* Domande frequenti sul caching edge BlueXP
+
** Consulta un elenco di domande e risposte frequenti https://bluexp.netapp.com/global-file-cache-faq["qui"^]


* https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["Guida utente Global file cache"^]
* Documentazione sui prodotti NetApp
+
** Consultare la documentazione aggiuntiva per i prodotti cloud NetApp https://docs.netapp.com/us-en/cloud/["qui"^]
** Consultare la documentazione aggiuntiva per tutti i prodotti NetApp https://www.netapp.com/support-and-training/documentation/["qui"^]


* Il supporto clienti per gli utenti di edge caching BlueXP con Cloud Volumes ONTAP è disponibile attraverso i seguenti canali:
+
** Risoluzione guidata dei problemi, Gestione dei casi, Knowledge base, Download, Strumenti, e molto altro ancora https://bluexp.netapp.com/gfc-support["qui"^]
** Accedere al supporto NetApp all'indirizzo https://mysupport.netapp.com[] Con le tue credenziali NSS
** Per assistenza immediata per un problema P1, chiamare il numero: +1 856.481.3990 (opzione 2)


* Il supporto clienti per gli utenti di edge caching BlueXP che utilizzano servizi Cloud Volumes e Azure NetApp Files è disponibile attraverso il supporto standard del tuo provider. Contattare rispettivamente il supporto clienti Google o il supporto clienti Microsoft.

