---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, gfc, global file cache' 
summary: Scopri le novità del caching edge BlueXP. 
---
= Novità del caching edge BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le novità del caching edge BlueXP.



== 31 maggio 2024

NetApp ha annunciato la fine della disponibilità (EOA) di NetApp Global file cache al 31 maggio 2024. La fine del ciclo di vita interessa tutti i prodotti NetApp Global file cache, incluse le sottoscrizioni software Global file cache standalone e le soluzioni in bundle Global file cache con NetApp Cloud Volumes ONTAP, note come NetApp Cloud Volumes Edge cache.

NetApp continuerà a supportare questi prodotti per i clienti esistenti per un minimo di 3 anni. https://mysupport.netapp.com/info/communications/CPC-00578.html["Vedi i dettagli della fine della disponibilità di Global file cache di NetApp"^].

Inoltre, è stata rimossa la possibilità di abilitare, implementare e gestire i componenti Global file cache dall'interfaccia utente BlueXP.



== 6 maggio 2024 (versione 2,4)

Questa versione risolve alcuni problemi minori. Il pacchetto software aggiornato è disponibile all'indirizzo https://docs.netapp.com/us-en/bluexp-edge-caching/download-gfc-resources.html#download-required-resources["questa pagina"].



== 1 agosto 2023 (versione 2,3)

Questa versione risolve i problemi descritti in https://docs.netapp.com/us-en/bluexp-edge-caching/fixed-issues.html["Problemi risolti"]. I pacchetti software aggiornati sono disponibili all'indirizzo https://docs.netapp.com/us-en/bluexp-edge-caching/download-gfc-resources.html#download-required-resources["questa pagina"].



== 5 aprile 2023 (versione 2.2)

Questa versione offre le nuove funzionalità elencate di seguito. Risolve inoltre i problemi descritti in https://docs.netapp.com/us-en/bluexp-edge-caching/fixed-issues.html["Problemi risolti"].



=== Supporto per Global file cache su sistemi Cloud Volumes ONTAP implementati in Google Cloud

Una nuova licenza "Edge cache" è disponibile quando si implementa un sistema Cloud Volumes ONTAP in Google Cloud. Hai diritto a implementare un sistema edge Global file cache per ogni 3 TIB di capacità acquistata sul sistema Cloud Volumes ONTAP.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#packages["Scopri di più sul pacchetto di licenza Edge cache."]



=== La configurazione guidata e l'interfaccia utente di configurazione GFC sono state migliorate per eseguire la registrazione della licenza NetApp



=== Optimus PSM ottimizzato per configurare la funzionalità Edge Sync



== 24 ottobre 2022 (versione 2.1)

Questa versione offre le nuove funzionalità elencate di seguito. Risolve inoltre i problemi descritti in https://docs.netapp.com/us-en/bluexp-edge-caching/fixed-issues.html["Problemi risolti"].



=== Global file cache è ora disponibile con un numero qualsiasi di licenze

Il precedente requisito minimo di 10 licenze, o 30 TB di storage, è stato rimosso. Verrà rilasciata una licenza Global file cache per ogni 3 TB di storage.



=== È stato aggiunto il supporto per l'utilizzo di un server di gestione delle licenze offline

Un server di gestione delle licenze (LMS) non in linea, o sito oscuro, è particolarmente utile quando il sistema LMS non dispone di una connessione Internet per la convalida delle licenze con le origini delle licenze. Durante la configurazione iniziale, è necessario disporre di una connessione a Internet e di una connessione all'origine della licenza. Una volta configurata, l'istanza di LMS può diventare scura. Tutti i bordi/core devono avere una connessione con LMS per la convalida continua delle licenze.



=== Le istanze edge possono supportare altri utenti simultanei

Una singola istanza Global file cache Edge può servire fino a 500 utenti per istanza fisica Edge dedicata e fino a 300 utenti per implementazioni virtuali dedicate. Il numero massimo di utenti utilizzato era 400 e 200, rispettivamente.



=== Optimus PSM ottimizzato per configurare le licenze cloud



=== È stata migliorata la funzione Edge Sync nell'interfaccia utente di Optimus (configurazione Edge) per mostrare tutti i client connessi



== 25 luglio 2022 (versione 2.0)

Questa versione offre le nuove funzionalità elencate di seguito. Risolve inoltre i problemi descritti in https://docs.netapp.com/us-en/bluexp-edge-caching/fixed-issues.html["Problemi risolti"].



=== Nuovo modello di licenza basato sulla capacità per Global file cache attraverso Azure Marketplace

Una nuova licenza "Edge cache" ha le stesse funzionalità della licenza "CVO Professional", ma include anche il supporto per Global file cache. Questa opzione viene visualizzata quando si implementa un nuovo sistema Cloud Volumes ONTAP in Azure. Hai diritto a implementare un sistema edge Global file cache per ogni 3 TIB di capacità fornita sul sistema Cloud Volumes ONTAP. È necessario eseguire il provisioning di un minimo di 30 TIB. Il servizio GFC License Manager è stato migliorato per fornire licenze basate sulla capacità.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#capacity-based-licensing["Scopri di più sul pacchetto di licenza Edge cache."]



=== Global file cache è ora integrato con Cloud Insights

NetApp Cloud Insights (ci) offre una visibilità completa dell'infrastruttura e delle applicazioni. Global file cache è ora integrato con ci per fornire una visibilità completa di tutti i core e i margini, monitorando i processi in esecuzione sulle istanze. Varie metriche Global file cache vengono inviate al ci per fornire una panoramica completa sul dashboard ci. Vedere il capitolo 11 della https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.1.0%20User%20Guide.pdf["Guida utente di NetApp Global file cache"^]

https://cloud.netapp.com/cloud-insights["Scopri di più su Cloud Insights."]



=== License Management Server è stato migliorato per funzionare in ambienti molto restrittivi

Durante la configurazione della licenza, il License Management Server (LMS) deve avere accesso a Internet per raccogliere i dettagli della licenza da NetApp/Zuora. Una volta completata la configurazione, il sistema LMS può continuare a lavorare in modalità offline e fornire funzionalità di licenza anche se si trova in ambienti restrittivi.



=== L'interfaccia utente di Edge Sync in Optimus è stata migliorata per mostrare l'elenco dei client connessi su un Edge coordinatore
